combat-log:
  # =========================
  # Core settings
  # =========================
  timer:
    duration-seconds: 15                 # Combat timer duration
    display: actionbar                   # actionbar | bossbar

  restrictions:
    elytra:
      disabled-in-combat: true
    teleporting:
      disabled-in-combat: false          # Disable any teleport while in combat
    mending:
      disabled-in-combat: true
    riptide:
      stop: false
      cooldown: 10000                    # riptide cooldown (sec * 100)
    explosions:
      set-combat-on-explosion: true      # End crystals + block explosions set combat

  punishment:
    damage: 5.0                          # Damage penalty for restricted actions (0 = off)
    kill-on-logout: false                # Kill player if they log out in combat

  # =========================
  # Special triggers
  # =========================
  triggers:
    enderpearl:
      set-combat-on-land: true           # Pearl on land triggers combat
      only-if-already-in-combat: false   # If false: pearl can start combat

  # =========================
  # Exclusions / blocks
  # =========================
  ignored-worlds:
    - "ffa"                              # Worlds where combat timer is ignored

  blocked-commands:
    - "tpa"                              # Commands blocked during combat

  # =========================
  # Combat zone
  # =========================
  combat-zone:
    enabled: true
    radius: 10

  # =========================
  # Messages
  # =========================
  messages:
    combat-log: "&c{player} has combat logged!"
    elytra-use-denied: "&dYou can't use elytra in combat"
    teleporting-denied: "&dYou can't teleport in combat"
    blocked-command: "&cYou can't use this command in combat"
    region-entry-denied: "&cYou can't enter this region in combat"

    timer:
      actionbar: "&c{timeLeft}/{maxTime}"
      bossbar-title: "&cIn Combat: {timeLeft}s"


anti-kill-abuse:
  enabled: true

  limits:
    max-kills: 5                          # more than 5 kills = abuse
    remove-kill-after-seconds: 60         # kill removed from list after X seconds

  punish-commands:
    - "kick {killer} Kill-Abuse detected!"
    - "ban {killer}"
